# coding: utf-8

"""
    StorageQuery API

    This document describes all operations that can be executed on the StorageQuery API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import storagequery
from storagequery.models.response_data_access_sql import ResponseDataAccessSql  # noqa: E501
from storagequery.rest import ApiException

class TestResponseDataAccessSql(unittest.TestCase):
    """ResponseDataAccessSql unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ResponseDataAccessSql
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = storagequery.models.response_data_access_sql.ResponseDataAccessSql()  # noqa: E501
        if include_optional :
            return ResponseDataAccessSql(
                response_time = 0.245, 
                content = [
                    None
                    ]
            )
        else :
            return ResponseDataAccessSql(
        )

    def testResponseDataAccessSql(self):
        """Test ResponseDataAccessSql"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
