# coding: utf-8

"""
    StorageQuery API

    This document describes all operations that can be executed on the StorageQuery API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import storagequery
from storagequery.models.success_response_data_access_sql import SuccessResponseDataAccessSql  # noqa: E501
from storagequery.rest import ApiException

class TestSuccessResponseDataAccessSql(unittest.TestCase):
    """SuccessResponseDataAccessSql unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SuccessResponseDataAccessSql
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = storagequery.models.success_response_data_access_sql.SuccessResponseDataAccessSql()  # noqa: E501
        if include_optional :
            return SuccessResponseDataAccessSql(
                response_time = 0.245, 
                content = [
                    None
                    ]
            )
        else :
            return SuccessResponseDataAccessSql(
        )

    def testSuccessResponseDataAccessSql(self):
        """Test SuccessResponseDataAccessSql"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
