# coding: utf-8

"""
    StorageQuery API

    This document describes all operations that can be executed on the StorageQuery API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from storagequery.configuration import Configuration


class BodyDataAccessSql(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'query': 'str',
        'bypass_cache': 'bool'
    }

    attribute_map = {
        'query': 'query',
        'bypass_cache': 'bypass-cache'
    }

    def __init__(self, query=None, bypass_cache=None, local_vars_configuration=None):  # noqa: E501
        """BodyDataAccessSql - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._query = None
        self._bypass_cache = None
        self.discriminator = None

        self.query = query
        if bypass_cache is not None:
            self.bypass_cache = bypass_cache

    @property
    def query(self):
        """Gets the query of this BodyDataAccessSql.  # noqa: E501

        Defines the SQL query string that the user wants to run on data connections.  # noqa: E501

        :return: The query of this BodyDataAccessSql.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this BodyDataAccessSql.

        Defines the SQL query string that the user wants to run on data connections.  # noqa: E501

        :param query: The query of this BodyDataAccessSql.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and query is None:  # noqa: E501
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    @property
    def bypass_cache(self):
        """Gets the bypass_cache of this BodyDataAccessSql.  # noqa: E501

        Defines a boolean flag indicating if the API should bypass possible internal cached results. The default is false.  # noqa: E501

        :return: The bypass_cache of this BodyDataAccessSql.  # noqa: E501
        :rtype: bool
        """
        return self._bypass_cache

    @bypass_cache.setter
    def bypass_cache(self, bypass_cache):
        """Sets the bypass_cache of this BodyDataAccessSql.

        Defines a boolean flag indicating if the API should bypass possible internal cached results. The default is false.  # noqa: E501

        :param bypass_cache: The bypass_cache of this BodyDataAccessSql.  # noqa: E501
        :type: bool
        """

        self._bypass_cache = bypass_cache

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BodyDataAccessSql):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BodyDataAccessSql):
            return True

        return self.to_dict() != other.to_dict()
