# coding: utf-8

"""
    StorageQuery API

    This document describes all operations that can be executed on the StorageQuery API.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from storagequery.configuration import Configuration


class SuccessResponseDataAccessSql(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'response_time': 'float',
        'content': 'list[object]'
    }

    attribute_map = {
        'response_time': 'response-time',
        'content': 'content'
    }

    def __init__(self, response_time=None, content=None, local_vars_configuration=None):  # noqa: E501
        """SuccessResponseDataAccessSql - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._response_time = None
        self._content = None
        self.discriminator = None

        if response_time is not None:
            self.response_time = response_time
        if content is not None:
            self.content = content

    @property
    def response_time(self):
        """Gets the response_time of this SuccessResponseDataAccessSql.  # noqa: E501


        :return: The response_time of this SuccessResponseDataAccessSql.  # noqa: E501
        :rtype: float
        """
        return self._response_time

    @response_time.setter
    def response_time(self, response_time):
        """Sets the response_time of this SuccessResponseDataAccessSql.


        :param response_time: The response_time of this SuccessResponseDataAccessSql.  # noqa: E501
        :type: float
        """

        self._response_time = response_time

    @property
    def content(self):
        """Gets the content of this SuccessResponseDataAccessSql.  # noqa: E501


        :return: The content of this SuccessResponseDataAccessSql.  # noqa: E501
        :rtype: list[object]
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this SuccessResponseDataAccessSql.


        :param content: The content of this SuccessResponseDataAccessSql.  # noqa: E501
        :type: list[object]
        """

        self._content = content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SuccessResponseDataAccessSql):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SuccessResponseDataAccessSql):
            return True

        return self.to_dict() != other.to_dict()
